httpcodes = {
	100: "Continue",
	101: "Switching protocols",
	200: "OK",
	201: "Created",
	202: "Accepted",
	203: "Non-authoritative information",
	204: "No content",
	205: "Reset content",
	206: "Partial content",
	300: "Multiple choices",
	301: "Moved permanently",
	302: "Found",
	303: "See other",
	304: "Not modified",
	305: "Use proxy",
	307: "Temporary redirect",
	400: "Bad request",
	401: "Unauthorized",
	403: "Forbidden",
	404: "Not found",
	405: "Method not allowed",
	406: "Not acceptable",
	407: "Proxy authentication required",
	408: "Request timeout",
	409: "Conflict",
	410: "Gone",
	411: "Length required",
	412: "Precondition failed",
	413: "Request entity too large",
	414: "Request URL too long",
	415: "Unsupported media type",
	416: "Requested range not satisfiable",
	417: "Expectation failed",
	500: "Internal server error",
	501: "Not implemented",
	502: "Bad gateway",
	503: "Service unavailable",
	504: "Gateway timeout",
	505: "HTTP version not supported"
}

ftpcodes = {
	110: "Restart marker replay",
	120: "Service ready in x minutes",
	125: "Data connection already open. Transfer starting",
	150: "File status okay; about to open data connection",
	202: "Command not implemented",
	211: "System status",
	212: "Directory status",
	213: "File status",
	214: "Help message",
	215: "NAME system type",
	220: "Service ready for new user",
	221: "Service closing control connection",
	225: "Data connection open; no transfer in progress",
	226: "Closing data connection",
	227: "Entering passive mode",
	228: "Entering long passive mode",
	229: "Entering extended passive mode",
	230: "User logged in, proceed",
	231: "User logged out",
	232: "Logout command noted",
	250: "Requested file action okay",
	257: "PATHNAME created",
	331: "Username okay, need password",
	332: "Need account for login",
	350: "Requested file action pending further information",
	421: "Service not available, closing control connection",
	425: "Can't open data connection",
	426: "Connection closed, transfer aborted",
	430: "Invalid username or password",
	434: "Requested host unavailable",
	450: "Requested file action not taken",
	451: "Requested action aborted",
	501: "Syntax error in parameters",
	502: "Command not implemented",
	503: "Bad sequence of commands",
	504: "Command not implemented for that parameter",
	530: "Not logged in",
	532: "Need account for storing files",
	550: "Requested action not taken",
	551: "Requested action aborted",
	552: "Requested file action aborted",
	553: "Requested action not taken"
}

smtpcodes = {
	200: "Nonstandard success response",
	211: "System status",
	214: "Help message",
	220: "Service ready",
	221: "Service closing transmission channel",
	250: "Requested mail action okay",
	251: "User not local, will forward",
	252: "Cannot VRFY user, but will accept",
	354: "Start mail input.",
	421: "Service not available",
	450: "Requested mail action not taken",
	451: "Requested action aborted",
	452: "Requested action not taken",
	500: "Syntax error",
	501: "Syntax error in parameters",
	502: "Command not implemented",
	503: "Bad sequence of commands",
	504: "Command parameter not implemented",
	521: "Does not accept mail",
	530: "Access denied",
	550: "Requested action not taken",
	551: "User not local",
	552: "Requested mail action aborted",
	553: "Requested action not taken",
	554: "Transaction failed"
}